### ISSUE TITLE
primary keys, unique at some level

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#11]
we need to make sure they will be unique when many datasets are being put together for an analysis.

**Comment by mobb** [comment]
options: 
1. code can prefix a package_id
2. recommendations for best practice, eg, see example ids.

**Comment by mobb** [comment]
related to #9

**Comment by clnsmth** [comment]
Unique primary keys can be created during the aggregation step. At this point each ecocomDP will have a data package identifier that can be concatenated with an abbreviated primary key name and primary key value (this is essentially option 1 above). 

An example of this is: knb-lter-hrf.118.28_obs_1107, where _obs_ denotes observation_id and _1107_ is the observation.

**Comment by clnsmth** [comment]
`validate_primary_keys` checks for unique primary keys within an L1, and has been added to the battery of validation tests in `validate_ecocomDP`. Globally unique primary keys will have to be created for L1 aggregation within the aggregation function (not yet written).
