### ISSUE TITLE
post the list of keywords

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#12]
They are in the notes, put them in the repo, in a way that they can be linked externally

**Comment by mobb** [comment]
Currently I have from the LTER vocab: Populations (corearea)
communities
community composition
community dynamics
community patterns
lakes
species composition
species diversity
species richness

**Comment by clnsmth** [comment]
I've posted this list of keywords (minus **lakes**, plus **ecocomDP**) in _EDIorg/ecocomDP/tree/master/inst_. This file can be accessed via the API with the command `GET /repos/:owner/:repo/contents/:path`. Go [here](https://developer.github.com/v3/repos/contents/) for additional info on getting repo contents.

**Comment by mobb** [comment]
There were terms in the notes (from the whiteboard); we should review these and include as needed.

**Comment by clnsmth** [comment]
Done.
