### ISSUE TITLE
reexamine popler

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#14]
the popler model was presented last week at ESA.  We should revisit it to see overlap. My impression is that ours is more general, but if popler has traction (e.g., via working groups), we should use it (or parts)

Note below from C, via slack: 
[8:31 AM] 
hey all, sitting in a Popler talk, it sure sounds like we should have used their database. I do remember deciding that it was too complicated ...

in the presentation it sounds like they already cleaned up the taxonomy for most of the LTER datasets

**Comment by mobb** [comment]
started a google doc, shared with the group. not linked here.

**Comment by clnsmth** [comment]
Close this issue @mobb?

**Comment by clnsmth** [comment]
This issue has been discussed in the ecocomDP paper.
