### ISSUE TITLE
Variables not available anymore

### ISSUE THREAD

**Issue by daijiang** [EDIorg/ecocomDP#152]
https://github.com/EDIorg/ecocomDP/blob/0554d64ce81f35ed59985d9d991203d88fe1621f/R/map_neon.ecocomdp.10043.001.001.R#L120

In the above line, it seems that the columns `totalWeight` and `subsampleWeight` are no longer available with the 2024 release of NEON mosquito data. @sokole Can you check this?

**Comment by daijiang** [comment]
And in Line 191:   https://github.com/EDIorg/ecocomDP/blob/0554d64ce81f35ed59985d9d991203d88fe1621f/R/map_neon.ecocomdp.10043.001.001.R#L191

**Comment by clnsmth** [comment]
Hi @daijiang. Thanks for reporting this issue. There may be a fix for it in the development branch. Would you mind installing the development branch and testing against it?

**Comment by daijiang** [comment]
@clnsmth will try and report back. Thanks!

**Comment by daijiang** [comment]
I think it worked. Thanks!

**Comment by clnsmth** [comment]
Thanks for testing @daijiang, this is helpful information!

I'm in the process pushing development to CRAN. The release should be cut in a few days (stay tuned).

**Comment by clnsmth** [comment]
The development branch is merged with main and the new release on CRAN.
