### ISSUE TITLE
sampling_location table required but column content is not

### ISSUE THREAD

**Issue by clnsmth** [EDIorg/ecocomDP#19]
Data pattern description ([here](https://github.com/EDIorg/ecocomDP/blob/master/documentation/model/table_description.md)) requires the _sampling_location_ table, however the table requires no more than a _sampling_location_id_. Is this correct? I thought _latitude_ and _longitude_ were minimum requirements.

**Comment by clnsmth** [comment]
One or more of the spatial attributes are required and is determined by the available metadata.

**Comment by mobb** [comment]
there are likely to be sites where all that is known is the id. eg, a quadrat along a transect, where the transect has a known lat/lon (e.g., for the start), but the quadrat has just an id. so the quad would have the transect as the parent
