### ISSUE TITLE
unique constraints for ecocomDP tables

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#22]
script should check that a group of fields in each table is unique: 
observation table:  
observation_id, event_id, package_id, sampling_location_id, observation_datetime, taxon_id, variable_name

others tbd. expect the uniq group to be all the ids (except the record_id) up through variable_name (not value or unit). in other words, each row is uniq except for record_id, value, unit

**Comment by clnsmth** [comment]
I'll integrate this into the validate_ecocomDP function.

**Comment by clnsmth** [comment]
Done. Checks added to `validate_ecocomDP` include:
 * primary keys
 * composite keys
 * referential integrity
