### ISSUE TITLE
distribution element should not refer to 'offline'

### ISSUE THREAD

**Issue by cgries** [EDIorg/ecocomDP#29]
When data are uploaded from desktop to PASTA currently the code inserts a statement that the data are 'offline' in the distribution element. That causes PASTA to display it as 'offline' even though the data are there and can be downloaded.

**Comment by clnsmth** [comment]
Thanks for this comment @cgries. [I've removed the 'offline' option from the make_eml function.](https://github.com/EDIorg/ecocomDP/commit/fef848de86b9653e6fcb05ddd646b3298be13e9e)
