### ISSUE TITLE
person ids cause problems 

### ISSUE THREAD

**Issue by cgries** [EDIorg/ecocomDP#30]
In some original EML files all people have an id associated. When those people are then re-used somewhere else (provenance) in the ecocomDP EML the ids clash because they have to be unique within one EML document. So, best is to strip out all id attributes associated with people information. E.g. <creator id="abrooks"> should be <creator>

**Comment by clnsmth** [comment]
Added a method to `make_eml` to remove IDs of creators and contacts listed in the provenance metadata.
