### ISSUE TITLE
write script to generate informational plots from datasets

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#35]
include a 1pp PDF as another data object.

examples from metacommunities WG here:
https://github.com/sokole/ltermetacommunities/tree/master/MS3-Supp-Info
their R-code is available. 

This group plotted
site vs. date (sampling homogeneity)
taxa total by plot (shared taxa) - plot similarity
taxon accumulation curve 
number of taxa/site/year (annual richness) to highlight possible changes to methods

**Comment by clnsmth** [comment]
The `plot_*()` functions do this.
