### ISSUE TITLE
Look at these other content models

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#40]
http://schemas.usgin.org/home/

Note: I got this link from an ESIP deep-dive on the NCEI "OneStop" data project (link below). In it Ken Casey references 3 "content models": 
this one
Darwin Core
a defunct website called nepanode.anl.gov
https://speakerd.s3.amazonaws.com/presentations/59c1a1caa9d94d9c89e61c0a2a2729aa/OneStop_ESIP_Tech_Deep_Dive_-_13_July_2016.pdf

**Comment by clnsmth** [comment]
We have looked at other content models and discussed in the ecocomDP paper.
