### ISSUE TITLE
EML template should include annotations, per v 2.2

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#43]
EML-2.2 will have annotations for dataset, entity, attribute.
some ecocom nodes map directly to terms in vocabs:
darwin core
humboldt core

related to #24, #42

**Comment by clnsmth** [comment]
The default set of L1 annotations is at [/inst/extdata/ecocomDP/annotations.txt](https://github.com/EDIorg/ecocomDP/blob/master/inst/extdata/ecocomDP/annotations.txt) and acted on by `create_eml()`.
