### ISSUE TITLE
add name of person performing the conversion to L1 metadata

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#47]
comment from the LTER ASM.  people would like to know who performed the conversion. 
TBD: where is metadata to put this. some candidate elements
metadataProvider
maintenance
[custom field in additionalMetadata]

should not be considered:
creator (creator is reserved for intell contributions, not processing)

**Comment by clnsmth** [comment]
Any decision on this?

**Comment by clnsmth** [comment]
This was fixed in e8165540722b0641471e7f4315e241848b847cd9.
