### ISSUE TITLE
suggest a sketch of sampling strategy

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#48]
we asked synth sci what was the easiest way for them to understand a sampling strategy. they said "visual" is much simpler than text. jpg is a good start.

add link here to Stevan session on lessons learned from synthesis: _______

**Comment by clnsmth** [comment]
Where do you envision this being implemented @mobb? A suggestion to data contributors at the time of archiving L0 data?

**Comment by clnsmth** [comment]
This falls within the scope of an L0 dataset. Not an L1.
