### ISSUE TITLE
add description of the ecocomDP model to dataset template

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#52]
Suggested by a user (@vanderbi): datasets should include a diagram to help users understand the layout of the tables.

**Comment by clnsmth** [comment]
Maybe this isn't necessary since the EML <abstract> links to the GitHub repo where the diagram and other project documentation lives?

**Comment by clnsmth** [comment]
No need to duplicate the model docs as L1 data entities since these are accessible via `view_diagram()` and `view_descriptions()` functions and linked to in the L1 EML.
