### ISSUE TITLE
Ensure that dataset/title does not use the <value> element

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#59]
dataset/title is mixed case. The canonical title goes at this xpath:
```eml:eml/dataset/title```

this xpath is for alternate titles, e.g., in other languages (and it also should have the lang="" attr)
```eml:eml/dataset/title/value```

alternate-language titles are customizations. they are not covered in EML BP (see the schema docs, though).  they are not likely to be in EMLprofile

**Comment by clnsmth** [comment]
This issue was fixed when branch fix_67 was merged with master (see 3d4f7bc3867c7a88230dfa65a09c9975a009ef38).
