### ISSUE TITLE
upgrade ecocomDP code to produce EML 2.2

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#62]
anticipating that DwC-A conversions, we will use attribute annotations. (DwC conversions are not dependent on EML 2.2, they can be 2.1)

Step 1. namespace change. 
Step 2. add DwC terms as annotations

**Comment by clnsmth** [comment]
Related to #43

**Comment by mobb** [comment]
Also to consider/discuss: L0 that are EML 2.2. 
- Should their L1 be EML 2.2 as well?
- which EML 2.2 features?
  - L0 attribute annotations (if these exist) should go into `variable_mapping` table
  - other features TBD (and probably need their own issues.)

**Comment by clnsmth** [comment]
The `create_eml()` handles this.
