### ISSUE TITLE
List of clean L1 packages for testing code against

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#92]
Colin's L1 checking code is great! but it is turning up problems in the L1, like duplicate PKs, duplicate rows, etc.
We need a list of known, good packages to check coding features against (eg, joins, pivots, etc)

Collect a list of clean L1 packages in this issue.

**Comment by clnsmth** [comment]
The L1 data package created in [this vignette](https://ediorg.github.io/ecocomDP/articles/create.html) is a good one (i.e. [edi.193](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.193.5)). Otherwise point `ecocomDP::read_data()` at one of the other published L1 data packages.
