### ISSUE TITLE
Code to pull lats/longs from L0 metadata, insert into L1 location table 

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#93]
many L0 packages have lats and longs only in EML metadata (geographicCoverage). L1>L2 conversions will not go back to the L0, so it would best if they have lats/longs in the location table. 

Create code to look for these in metadata, so they can go into the location table.

**Comment by clnsmth** [comment]
@mobb This is implemented, on a case by case basis, within an L0 to L1 create_ecocomDP.R script archived in an L1 data package. Any generally useful helper functions will be released with the R package.
